name: CI-CD-Pipeline

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: devops-cluster
  GKE_REGION: asia-south1
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v3
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v3

    - name: Install GKE Auth Plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin --quiet

    - name: Configure Docker
      run: |
        gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

    - name: Build Docker Image
      run: |
        docker build -t asia-south1-docker.pkg.dev/$PROJECT_ID/docker-repo/nodejs-app:latest ./app

    - name: Push Docker Image
      run: |
        docker push asia-south1-docker.pkg.dev/$PROJECT_ID/docker-repo/nodejs-app:latest

    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_REGION }}

    - name: Verify Cluster Connection
      run: |
        kubectl get nodes

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/namespace.yaml
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml